/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package interfaz;

/**
 *
 * @author user
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    public Principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtentero1 = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        txtnumerador1 = new javax.swing.JTextField();
        txtdenominador1 = new javax.swing.JTextField();
        cmboperaciones = new javax.swing.JComboBox<>();
        jSeparator2 = new javax.swing.JSeparator();
        txtentero2 = new javax.swing.JTextField();
        txtnumerador2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtdenominador2 = new javax.swing.JTextField();
        txtentero3 = new javax.swing.JTextField();
        txtnumerador3 = new javax.swing.JTextField();
        txtdenominador3 = new javax.swing.JTextField();
        cmdborrar = new javax.swing.JButton();
        cmdlimpiar = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jTextField10 = new javax.swing.JTextField();
        jSeparator4 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("OPERACIONES CON NUMEROS MIXTOS Y CONVERTIR A FRACCIONARIO");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 10, 450, 40));

        txtentero1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtentero1ActionPerformed(evt);
            }
        });
        jPanel1.add(txtentero1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 80, 50, 40));
        jPanel1.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, 80, 30));
        jPanel1.add(txtnumerador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 80, 30));
        jPanel1.add(txtdenominador1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 80, 30));

        cmboperaciones.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sumado", "Restado", "Multiplicado", "Dividio" }));
        jPanel1.add(cmboperaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 90, 120, 30));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 100, 120, 10));

        txtentero2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtentero2ActionPerformed(evt);
            }
        });
        jPanel1.add(txtentero2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, 60, 40));
        jPanel1.add(txtnumerador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 60, 90, 30));

        jLabel2.setText("=");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 200, 30, 20));
        jPanel1.add(txtdenominador2, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 110, 90, 30));
        jPanel1.add(txtentero3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 200, 50, 30));
        jPanel1.add(txtnumerador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 90, 30));
        jPanel1.add(txtdenominador3, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 220, 90, 30));

        cmdborrar.setText("Calcular");
        jPanel1.add(cmdborrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 200, 100, 30));

        cmdlimpiar.setText("Limpiar");
        jPanel1.add(cmdlimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 240, 100, 30));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 210, 130, 10));

        jLabel3.setText("Convetido");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 100, -1));
        jPanel1.add(jTextField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 110, 30));

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField10, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, 110, 30));
        jPanel1.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 230, 110, 10));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 450));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtentero1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtentero1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtentero1ActionPerformed

    private void txtentero2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtentero2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtentero2ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> cmboperaciones;
    private javax.swing.JButton cmdborrar;
    private javax.swing.JButton cmdlimpiar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField txtdenominador1;
    private javax.swing.JTextField txtdenominador2;
    private javax.swing.JTextField txtdenominador3;
    private javax.swing.JTextField txtentero1;
    private javax.swing.JTextField txtentero2;
    private javax.swing.JTextField txtentero3;
    private javax.swing.JTextField txtnumerador1;
    private javax.swing.JTextField txtnumerador2;
    private javax.swing.JTextField txtnumerador3;
    // End of variables declaration//GEN-END:variables
}
